# Argus DNS resolver and blocklists.
# Source after argus/lib.sh (needs ARGUS_* paths and policy).

argus_dns_dirs() {
	ARGUS_DNS_DIR="${SHARED_DIR}/argus-dns"
	ARGUS_DNS_CACHE="${ARGUS_DNS_DIR}/cache"
	ARGUS_DNS_CONF="${ARGUS_DNS_DIR}/dnsmasq.conf"
	ARGUS_DNS_BLOCK_CONF="${ARGUS_DNS_DIR}/blocklist.conf"
	ARGUS_DNS_PID="${ARGUS_DNS_DIR}/dnsmasq.pid"
	ARGUS_DNS_LOG="${ARGUS_DNS_DIR}/dnsmasq.log"
	# User-writable map so status can enrich connections without root.
	ARGUS_DNS_IPMAP="${XDG_RUNTIME_DIR:-/tmp}/mvm-argus-dns.ipmap"
	ARGUS_DNS_LOCAL_LISTS="${ARGUS_DIR}/blocklists"
	ARGUS_DNS_ALLOWLIST="${ARGUS_DIR}/allowlist.txt"
}

argus_dns_defaults() {
	ARGUS_DNS_ENABLED="${ARGUS_DNS_ENABLED:-1}"
	ARGUS_DNS_FORCE="${ARGUS_DNS_FORCE:-1}"
	ARGUS_DNS_UPSTREAM="${ARGUS_DNS_UPSTREAM:-1.1.1.1,9.9.9.9}"
	ARGUS_DNS_PORT="${ARGUS_DNS_PORT:-53}"
	ARGUS_DNS_LOG_QUERIES="${ARGUS_DNS_LOG_QUERIES:-1}"
	ARGUS_DNS_QUERY_LINES="${ARGUS_DNS_QUERY_LINES:-40}"
	# Comma-separated URLs. Empty uses the built-in default hosts list.
	ARGUS_DNS_BLOCKLIST_URLS="${ARGUS_DNS_BLOCKLIST_URLS:-}"
	ARGUS_DNS_UPDATE_ON_APPLY="${ARGUS_DNS_UPDATE_ON_APPLY:-0}"
}

argus_dns_default_urls() {
	# StevenBlack unified hosts (ads malware fake news) is a common public list.
	printf '%s\n' "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
}

argus_dns_fetch_lists() {
	argus_dns_dirs
	mkdir -p "${ARGUS_DNS_CACHE}" "${ARGUS_DNS_LOCAL_LISTS}"

	url=
	i=0
	dest=
	_adf_old_ifs=

	if [ -n "${ARGUS_DNS_BLOCKLIST_URLS}" ]; then
		_adf_old_ifs=${IFS}
		IFS=,
		for url in ${ARGUS_DNS_BLOCKLIST_URLS}; do
			IFS=${_adf_old_ifs}
			url="$(echo "${url}" | tr -d '[:space:]')"
			[ -n "${url}" ] || continue
			i=$((i + 1))
			dest="${ARGUS_DNS_CACHE}/remote-${i}.list"
			info "fetching blocklist ${url}"
			if ! curl -fsSL --connect-timeout 20 --max-time 120 -o "${dest}.partial" "${url}"; then
				echo "warn: failed to fetch ${url}" >&2
				rm -f "${dest}.partial"
				continue
			fi
			mv -f "${dest}.partial" "${dest}"
			IFS=,
		done
		IFS=${_adf_old_ifs}
	else
		i=0
		argus_dns_default_urls | while read -r url; do
			url="$(echo "${url}" | tr -d '[:space:]')"
			[ -n "${url}" ] || continue
			i=$((i + 1))
			dest="${ARGUS_DNS_CACHE}/remote-${i}.list"
			info "fetching blocklist ${url}"
			if ! curl -fsSL --connect-timeout 20 --max-time 120 -o "${dest}.partial" "${url}"; then
				echo "warn: failed to fetch ${url}" >&2
				rm -f "${dest}.partial"
				continue
			fi
			mv -f "${dest}.partial" "${dest}"
		done
	fi
}

argus_dns_compile() {
	argus_dns_dirs
	require_cmd python3
	mkdir -p "${ARGUS_DNS_DIR}"

	_adc_list_file=$(mktemp)
	f=
	for f in "${ARGUS_DNS_CACHE}"/*.list "${ARGUS_DNS_LOCAL_LISTS}"/*.list; do
		[ -f "${f}" ] || continue
		printf '%s\n' "${f}" >>"${_adc_list_file}"
	done

	if [ ! -s "${_adc_list_file}" ]; then
		: >"${ARGUS_DNS_BLOCK_CONF}"
		echo "no blocklists present (add files under argus/blocklists or fetch URLs)"
		rm -f "${_adc_list_file}"
		return 0
	fi

	# Word-split paths on newlines for the compiler argv.
	# shellcheck disable=SC2046
	set -- $(tr '\n' ' ' <"${_adc_list_file}")
	rm -f "${_adc_list_file}"
	python3 "${ARGUS_DIR}/compile-blocklists.py" \
		"${ARGUS_DNS_ALLOWLIST}" \
		"${ARGUS_DNS_BLOCK_CONF}" \
		"$@"
}

argus_dns_write_dnsmasq_conf() {
	argus_dns_dirs
	conf_queries=""
	first=1

	mkdir -p "${ARGUS_DNS_DIR}"

	if [ "${ARGUS_DNS_LOG_QUERIES}" = "1" ]; then
		conf_queries="log-queries"
	fi

	cat >"${ARGUS_DNS_CONF}" <<EOF
# Generated by Argus. Do not edit by hand.
listen-address=${GATEWAY_IP}
bind-interfaces
interface=${BRIDGE_NAME}
except-interface=lo
port=${ARGUS_DNS_PORT}
no-resolv
no-hosts
bogus-priv
domain-needed
cache-size=2000
conf-file=${ARGUS_DNS_BLOCK_CONF}
pid-file=${ARGUS_DNS_PID}
log-facility=${ARGUS_DNS_LOG}
${conf_queries}
EOF

	_adu_old_ifs=${IFS}
	IFS=,
	for upstream in ${ARGUS_DNS_UPSTREAM}; do
		IFS=${_adu_old_ifs}
		upstream="$(echo "${upstream}" | tr -d '[:space:]')"
		[ -n "${upstream}" ] || continue
		echo "server=${upstream}" >>"${ARGUS_DNS_CONF}"
		first=0
		IFS=,
	done
	IFS=${_adu_old_ifs}
	if [ "${first}" -eq 1 ]; then
		echo "server=1.1.1.1" >>"${ARGUS_DNS_CONF}"
	fi
}

argus_dns_stop() {
	argus_dns_dirs
	pid=
	if [ -f "${ARGUS_DNS_PID}" ]; then
		pid="$(cat "${ARGUS_DNS_PID}" 2>/dev/null || true)"
		if [ -n "${pid}" ] && kill -0 "${pid}" 2>/dev/null; then
			kill "${pid}" 2>/dev/null || true
			sleep 1 || true
			kill -9 "${pid}" 2>/dev/null || true
		fi
		rm -f "${ARGUS_DNS_PID}"
	fi
	# Fallback if pid file is stale.
	pkill -f "dnsmasq .*-C ${ARGUS_DNS_CONF}" 2>/dev/null || true
}

argus_dns_start() {
	argus_dns_dirs
	require_cmd dnsmasq

	argus_dns_stop
	argus_dns_write_dnsmasq_conf

	# Ensure bridge address exists so dnsmasq can bind.
	setup_bridge

	# Pre-create the log as world-readable so ./mvm argus status works without root.
	: >>"${ARGUS_DNS_LOG}"
	chmod 644 "${ARGUS_DNS_LOG}" 2>/dev/null || true

	dnsmasq -C "${ARGUS_DNS_CONF}"
	sleep 1
	chmod 644 "${ARGUS_DNS_LOG}" 2>/dev/null || true
	if [ -f "${ARGUS_DNS_PID}" ] && kill -0 "$(cat "${ARGUS_DNS_PID}")" 2>/dev/null; then
		echo "argus dns listening on ${GATEWAY_IP}:${ARGUS_DNS_PORT} (pid $(cat "${ARGUS_DNS_PID}"))"
	else
		die "dnsmasq failed to start (see ${ARGUS_DNS_LOG})"
	fi
}

argus_dns_apply() {
	argus_dns_defaults

	if [ "${ARGUS_DNS_ENABLED}" != "1" ]; then
		argus_dns_stop
		echo "argus dns disabled"
		return 0
	fi

	if [ "${ARGUS_DNS_UPDATE_ON_APPLY}" = "1" ] || [ ! -d "${SHARED_DIR}/argus-dns/cache" ] \
		|| [ -z "$(ls -A "${SHARED_DIR}/argus-dns/cache" 2>/dev/null || true)" ]; then
		argus_dns_fetch_lists
	fi

	argus_dns_compile
	argus_dns_start
}

argus_dns_update() {
	argus_dns_defaults
	[ "${ARGUS_DNS_ENABLED}" = "1" ] || die "ARGUS_DNS_ENABLED is not 1"
	argus_require_root
	argus_dns_fetch_lists
	argus_dns_compile
	argus_dns_start
}

argus_dns_status() {
	argus_dns_dirs
	argus_dns_defaults

	echo "Argus DNS"
	echo "  enabled:     ${ARGUS_DNS_ENABLED}"
	echo "  force:       ${ARGUS_DNS_FORCE}"
	echo "  listen:      ${GATEWAY_IP}:${ARGUS_DNS_PORT}"
	echo "  upstream:    ${ARGUS_DNS_UPSTREAM}"
	echo "  log queries: ${ARGUS_DNS_LOG_QUERIES}"
	echo "  conf:        ${ARGUS_DNS_CONF}"
	echo "  block conf:  ${ARGUS_DNS_BLOCK_CONF}"
	echo "  query log:   ${ARGUS_DNS_LOG}"

	dpid="$(tr -d '[:space:]' <"${ARGUS_DNS_PID}" 2>/dev/null || true)"
	if [ -n "${dpid}" ] && [ -r "/proc/${dpid}/cmdline" ] \
		&& tr '\0' ' ' <"/proc/${dpid}/cmdline" | grep -q dnsmasq; then
		echo "  dnsmasq:     running pid ${dpid}"
	else
		echo "  dnsmasq:     stopped"
	fi

	if [ -f "${ARGUS_DNS_BLOCK_CONF}" ]; then
		echo "  blocked:     $(grep -c '^address=' "${ARGUS_DNS_BLOCK_CONF}" 2>/dev/null || echo 0) domains"
	else
		echo "  blocked:     0 domains"
	fi
}

argus_dns_show_queries() {
	# Recent guest DNS lookups with allowed/blocked outcome.
	argus_dns_dirs
	argus_dns_defaults
	lines="${1:-${ARGUS_DNS_QUERY_LINES}}"
	filter_name="${2:-}"

	if [ "${ARGUS_DNS_LOG_QUERIES}" != "1" ]; then
		echo "(DNS query logging is off set ARGUS_DNS_LOG_QUERIES=1 and run sudo ./mvm argus apply)"
		return 0
	fi
	if [ ! -f "${ARGUS_DNS_LOG}" ]; then
		echo "(no DNS query log yet)"
		return 0
	fi

	_rows_file=$(mktemp)
	argus_foreach_instance >"${_rows_file}"
	python3 - "${ARGUS_DNS_LOG}" "${lines}" "${filter_name}" "${SUBNET_PREFIX}" "${ARGUS_DNS_IPMAP}" "${_rows_file}" <<'PY'
import sys
from collections import OrderedDict
from pathlib import Path

log_path = sys.argv[1]
limit = int(sys.argv[2])
filter_name = sys.argv[3]
subnet = sys.argv[4] + "."
map_path = sys.argv[5]
rows = Path(sys.argv[6]).read_text(encoding="utf-8", errors="replace").splitlines()

ip_to_name = {}
for row in rows:
    parts = row.split("\t")
    if len(parts) >= 2 and parts[1]:
        ip_to_name[parts[1]] = parts[0]

# pending (src, domain) -> qtype
pending = {}
# events newest last: (src, domain, qtype, action)
events = []
# resolved answer IP -> domain
ip_domain = {}

def looks_like_ip(s):
    if not s:
        return False
    if s[0].isdigit():
        return True
    return ":" in s

def find_pending(domain):
    for (s, d), qt in list(pending.items()):
        if d == domain:
            return s, qt
    return "", "A"

try:
    with open(log_path, "r", encoding="utf-8", errors="replace") as fh:
        lines = fh.readlines()
except OSError:
    print("(unable to read DNS query log)")
    raise SystemExit(0)

for line in lines:
    line = line.strip()
    if "query[" not in line and "config " not in line and "reply " not in line and "cached " not in line:
        continue

    # query[A] example.com from 10.100.0.10
    if "query[" in line and " from " in line:
        try:
            qpart = line.split("query[", 1)[1]
            qtype = qpart.split("]", 1)[0]
            rest = qpart.split("]", 1)[1].strip()
            domain, _, src = rest.partition(" from ")
            domain = domain.strip().rstrip(".")
            src = src.strip()
            if not src.startswith(subnet):
                continue
            pending[(src, domain)] = qtype
            events.append((src, domain, qtype, "query"))
        except Exception:
            pass
        continue

    # config ads.example.com is 0.0.0.0 (blocklist sinkhole)
    if " config " in line and " is " in line:
        try:
            body = line.split(" config ", 1)[1]
            domain, _, answer = body.partition(" is ")
            domain = domain.strip().rstrip(".")
            answer = answer.strip().split()[0]
            src, qtype = find_pending(domain)
            if not src:
                continue
            action = "blocked" if answer in {"0.0.0.0", "::", "NXDOMAIN"} or answer.startswith("NODATA") else "config"
            events.append((src, domain, qtype, action))
            if action != "blocked" and looks_like_ip(answer):
                ip_domain[answer] = domain
        except Exception:
            pass
        continue

    # reply example.com is 1.2.3.4
    # cached example.com is 1.2.3.4
    for kind in (" reply ", " cached "):
        if kind in line and " is " in line:
            try:
                body = line.split(kind, 1)[1]
                domain, _, answer = body.partition(" is ")
                domain = domain.strip().rstrip(".")
                answer = answer.strip().split()[0]
                src, qtype = find_pending(domain)
                if src:
                    events.append((src, domain, qtype, "allowed"))
                if looks_like_ip(answer) and answer not in {"0.0.0.0", "::"}:
                    ip_domain[answer] = domain
            except Exception:
                pass
            break

# Collapse to one row per (src, domain, qtype). Outcomes override bare queries.
final = OrderedDict()
for src, domain, qtype, action in events:
    key = (src, domain, qtype)
    if action == "query" and key in final:
        continue
    final[key] = action

rows_out = []
for (src, domain, qtype), action in final.items():
    if action == "query":
        action = "lookup"
    name = ip_to_name.get(src, src)
    if filter_name and filter_name not in (name, src):
        continue
    rows_out.append((name, domain, qtype, action))

rows_out = rows_out[-limit:]
if not rows_out:
    print("(no guest DNS queries logged yet)")
else:
    print(f"{'INSTANCE':<14} {'DOMAIN':<42} {'TYPE':<6} {'RESULT'}")
    print("-" * 78)
    for name, domain, qtype, action in rows_out:
        print(f"{name:<14} {domain:<42} {qtype:<6} {action}")

# Persist IP to domain map for connection enrichment in status.
try:
    with open(map_path, "w", encoding="utf-8") as fh:
        for ip, domain in sorted(ip_domain.items()):
            fh.write(f"{ip}\t{domain}\n")
except OSError:
    pass
PY
}
