#!/bin/sh
# Install a passwordless doas rule for mvm lifecycle commands.
#
# Usage:
#   doas ./scripts/doas-install.sh
#   doas ./scripts/doas-install.sh --user alice
#   doas ./scripts/doas-install.sh --remove

set -eu

# shellcheck source=../lib/common.sh
. "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)/lib/common.sh"
load_config

TARGET_USER="${DOAS_USER:-${SUDO_USER:-${USER:-}}}"
REMOVE=0
WRAPPER="${MVM_WRAPPER:-/usr/local/sbin/mvm}"
DOAS_CONF="${MVM_DOAS_CONF:-/etc/doas.conf}"
DOAS_MARKER_BEGIN="# BEGIN mvm"
DOAS_MARKER_END="# END mvm"

while [ $# -gt 0 ]; do
	case "$1" in
	--user)
		TARGET_USER="$2"
		shift 2
		;;
	--remove)
		REMOVE=1
		shift
		;;
	-h|--help)
		sed -n '2,8p' "$0" | sed 's/^# \{0,1\}//'
		exit 0
		;;
	*)
		die "unknown option: $1"
		;;
	esac
done

require_root
command -v doas >/dev/null 2>&1 || die "doas not found on PATH"

strip_mvm_block() {
	src="$1"
	dest="$2"
	if [ ! -f "${src}" ]; then
		: >"${dest}"
		return 0
	fi
	awk -v begin="${DOAS_MARKER_BEGIN}" -v end="${DOAS_MARKER_END}" '
		$0 == begin { skip = 1; next }
		$0 == end { skip = 0; next }
		!skip { print }
	' "${src}" >"${dest}"
}

if [ "${REMOVE}" = "1" ]; then
	if [ -f "${DOAS_CONF}" ]; then
		tmp="$(mktemp)"
		strip_mvm_block "${DOAS_CONF}" "${tmp}"
		mv -f "${tmp}" "${DOAS_CONF}"
		chmod 600 "${DOAS_CONF}" 2>/dev/null || true
	fi
	if [ -f "${WRAPPER}" ] && grep -q "mvm wrapper" "${WRAPPER}" 2>/dev/null; then
		rm -f "${WRAPPER}"
	fi
	echo "removed mvm block from ${DOAS_CONF}"
	exit 0
fi

if [ -z "${TARGET_USER}" ] || [ "${TARGET_USER}" = "root" ]; then
	die "pass --user <name> (refusing to install for root)"
fi

id "${TARGET_USER}" >/dev/null 2>&1 || die "user not found: ${TARGET_USER}"
MVM="$(mvm_bin)"
[ -f "${MVM}" ] || die "missing ${MVM}"
chmod +x "${MVM}"

mkdir -p "$(dirname "${WRAPPER}")"
cat >"${WRAPPER}" <<EOF
#!/bin/sh
# mvm wrapper generated by doas-install
exec "${MVM}" "\$@"
EOF
chmod 755 "${WRAPPER}"

tmp_base="$(mktemp)"
tmp_out="$(mktemp)"
strip_mvm_block "${DOAS_CONF}" "${tmp_base}"
{
	cat "${tmp_base}"
	[ -s "${tmp_base}" ] && echo
	cat <<EOF
${DOAS_MARKER_BEGIN}
# Managed by mvm doas-install. Passwordless lifecycle for ${TARGET_USER}.
permit nopass keepenv ${TARGET_USER} as root cmd ${WRAPPER}
${DOAS_MARKER_END}
EOF
} >"${tmp_out}"

mv -f "${tmp_out}" "${DOAS_CONF}"
chmod 600 "${DOAS_CONF}"
rm -f "${tmp_base}"

echo "installed mvm rule in ${DOAS_CONF}"
echo "installed wrapper ${WRAPPER} -> ${MVM}"
echo "  ${TARGET_USER} can run: doas mvm <command> or doas ${WRAPPER} <command>"
echo "  try: doas mvm list"
