#!/bin/sh
# Install a passwordless sudoers rule for mvm lifecycle commands.
#
# Usage:
#   sudo ./scripts/sudoers-install.sh
#   sudo ./scripts/sudoers-install.sh --user alice
#   sudo ./scripts/sudoers-install.sh --remove

set -eu

# shellcheck source=../lib/common.sh
. "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)/lib/common.sh"
load_config

TARGET_USER="${SUDO_USER:-${USER:-}}"
REMOVE=0
WRAPPER="${MVM_WRAPPER:-/usr/local/sbin/mvm}"

while [ $# -gt 0 ]; do
	case "$1" in
	--user)
		TARGET_USER="$2"
		shift 2
		;;
	--remove)
		REMOVE=1
		shift
		;;
	-h|--help)
		sed -n '2,8p' "$0" | sed 's/^# \{0,1\}//'
		exit 0
		;;
	*)
		die "unknown option: $1"
		;;
	esac
done

require_root

SUDOERS_FILE="/etc/sudoers.d/mvm"
MVM="$(mvm_bin)"

if [ "${REMOVE}" = "1" ]; then
	rm -f "${SUDOERS_FILE}"
	if [ -f "${WRAPPER}" ] && grep -q "mvm wrapper" "${WRAPPER}" 2>/dev/null; then
		rm -f "${WRAPPER}"
	fi
	echo "removed ${SUDOERS_FILE}"
	exit 0
fi

if [ -z "${TARGET_USER}" ] || [ "${TARGET_USER}" = "root" ]; then
	die "pass --user <name> (refusing to install for root)"
fi

id "${TARGET_USER}" >/dev/null 2>&1 || die "user not found: ${TARGET_USER}"
[ -f "${MVM}" ] || die "missing ${MVM}"
chmod +x "${MVM}"

# Sudoers cannot reliably express paths with spaces, so install a stable wrapper.
mkdir -p "$(dirname "${WRAPPER}")"
cat >"${WRAPPER}" <<EOF
#!/bin/sh
# mvm wrapper generated by sudoers-install
exec "${MVM}" "\$@"
EOF
chmod 755 "${WRAPPER}"

tmp="$(mktemp)"
cat >"${tmp}" <<EOF
# Managed by mvm sudoers-install. Passwordless lifecycle for ${TARGET_USER}.
Defaults!${WRAPPER} env_keep += "MICROVM_MODE DETACH SETUP_NET HOST_SHARES MEM_MIB VCPU_COUNT PORT_FORWARDS PROFILE DATA_SIZE_MIB ROOTFS_SIZE_MIB BACKUP_ROOTFS"
${TARGET_USER} ALL=(root) NOPASSWD: ${WRAPPER}
EOF
chmod 440 "${tmp}"

if command -v visudo >/dev/null 2>&1; then
	visudo -cf "${tmp}" || {
		rm -f "${tmp}"
		die "sudoers snippet failed validation"
	}
fi

mv -f "${tmp}" "${SUDOERS_FILE}"
chmod 440 "${SUDOERS_FILE}"
echo "installed ${SUDOERS_FILE}"
echo "installed wrapper ${WRAPPER} -> ${MVM}"
echo "  ${TARGET_USER} can run: sudo mvm <command> or sudo ${WRAPPER} <command>"
echo "  try: sudo -n mvm list"
